[package]
name = "rorrim"
version = "0.1.0"
authors = ["Kleidi Bujari <dev@kleidi.ca>"]
edition = "2021"
description = "Downloading and filtering Arch Linux mirrors"
homepage = "https://github.com/kbzt/rorrim"
documentation = "https://github.com/kbzt/rorrim"
repository = "https://github.com/kbzt/rorrim"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
clap = { version = "4.0.32", features = ["derive"] }
reqwest = { version = "0.11.13", features = ["blocking", "json"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
