[package]
name = "mirro-rs"
version = "0.1.0"
authors = ["Kleidi Bujari <dev@kleidi.ca>"]
edition = "2021"
description = "Downloading and filtering Arch Linux mirrors"
repository = "https://github.com/kbzt/mirro-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
reqwest = { version = "0.11.13", features = ["blocking", "json"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
