name: build release
on:
  workflow_dispatch:
  release:
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          
      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked --verbose
        
      - name: Strip binary
        shell: bash
        run: strip "target/release/rorrim"
        
      - name: Build archive
        shell: bash
        run: |
          cp target/release/rorrim ./rorrim
          tar -czvf rorrim.tar.gz rorrim LICENSE README.md
          echo "ASSET=rorrim.tar.gz" >> $GITHUB_ENV
          
      - name: Save release as artifact
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: rorrim.tar.gz
